### ISSUE TITLE
安卓设备弹出气泡怎么设置Text文本内容？

### ISSUE THREAD

**Issue by 0FengQiang0** [lizubing1992/flutter_baidu_mapapi_map#2]
我使用的基础地图插件：flutter_baidu_mapapi_map: ^2.0.1
运行设备：安卓手机

下面是我的应用运行截图：
![53F597B2224A30C265DB3ADECF8ADEF7](https://user-images.githubusercontent.com/16080084/133872881-5435ba55-d94e-4063-9c4a-50cd7551bca9.png)

我往地图上添加了 BMFInfoWindow，无法自定义图片上显示的文本，因为BMFInfoWindow的构造函数只支持传入image，不支持自定义的 title 和 text

       BMFInfoWindow infoWindow = BMFInfoWindow(
         coordinate: BMFCoordinate(tempModel.latitude,tempModel.longitude),
         image: "images/map_infowindow_bg.png",
         yOffset: -50,
         isAddWithBitmap: true,
      );

期望：能够在弹出的BMFInfoWindow上自定义文本内容。
就是要实现下图在BMFInfoWindow 上添加自定义文本的效果：
![76DFEF0650D4FAE804EBB62B2E840AE1](https://user-images.githubusercontent.com/16080084/133873248-f160d7d9-d416-47b0-a692-78a29b5bdf78.png)

**Comment by lizubing1992** [comment]
显示文字，百度地图可以用BMFText ，不过可能无法满足你的需求，

**Comment by 0FengQiang0** [comment]
> 显示文字，百度地图可以用BMFText ，不过可能无法满足你的需求，

目前我的解决方法是：在iOS设备上给BMFMarker设置title和subtitle，在安卓设备上就用BMFText，这样点击BMFMarker时iOS和安卓就都能显示自定义文字内容了，只是iOS和安卓上显示效果不一样。希望百度地图flutter插件功能越来越强大。
